meta_title: "JusticeFantome.fr,le site anti-injustices"
meta_description: "Quand la justice est absente,dénoncez la.La discrimination est interdite par la loi et sanctionnée, malheureusement en France trop d'inégalités et trop de discriminations existent encore."
meta_image: "/app/assets/images/nojustice.jpeg" # Une image dans votre dossier app/assets/images/
